name: verify
run-name: verify commit
on: [pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g yarn
      - run: yarn install
#      - run: yarn lint
      - run: yarn dev # change to build when it will be working
      - run: yarn lint:state ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}